version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aumin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pasaux
      ME_CONFIG_MONGODB_SERVER: mongo
    restart: always

volumes:
  mongo-data: